[9월 16일] 부르트 포스
Altu-Bitu-3/Altu-Bitu-JiwooHong pull request #4
Opened 2022-09-21 17:36 UTC by ghdwldn0914

#### 내용 & 질문
> 9월 16일 부르트 포스 과제 제출합니다

#### <기존 제출>
> 2858

#### <추가 제출>
>

2022-09-22 17:04 UTC, bsa0322 requested changes
**p1. 2858 코드리뷰 완료**
지우님 안녕하세요 😊😊 코드 효율성 관련해 코멘트 남겼습니다! 수정하시거나 질문사항 있으시면 리뷰어로 호출 부탁드려요~! 수고하셨습니다 💘💘💘

2022-09-22 17:04 UTC, bsa0322 commented on 09월 16일 - 부르트 포스/2858.cpp
> +
p3. 전역변수 사용은 최대한 지양해주세요! 코드가 길어졌을 시, 전역변수로 선언한 변수로 지역변수로 선언하거나 수정되면 안되는 변수인데 수정이 되는 등의 혼란이 있을 수 있습니다 😊😊

2022-09-22 17:04 UTC, bsa0322 commented on 09월 16일 - 부르트 포스/2858.cpp
> +	}
p1. 가로, 세로 길이의 최소가 3이라는 점을 활용해서 브루트 포스적 접근을 아주 잘 해주셨네요!! 
지금도 좋지만, **해당 문제는 O(N) 으로 해결**할 수도 있어요.

깃허브 힌트로 **타일의 총 개수는 타일의 넓이**와 같을 거라 말씀드렸죠~! 저희는 직사각형의 넓이를 안다면, **가로와 세로 둘 중 하나의 길이만 알아도 다른 길이를 알 수가 있어요!** 그리고 가로와 세로 길이를 알면 지금처럼 빨간 타일과 갈색 타일의 개수를 구해 정답과 일치하는지 알 수 있겠죠 🥰 그리고 이때는, 직사각형의 넓이에 맞춰 가로와 세로의 길이를 구했을 테니까 **두 타일 중 하나만 비교해도 괜찮을 것 같아요.**

힌트 더 필요하시면 말씀해주세요~!

2022-09-24 08:03 UTC, kwakrhkr59 commented
**[추가제출 확인 완료]**
안녕하세요 지우님~ 추가제출 확인 완료되셨습니다😊
이번 과제도 수고 많으셨습니다:)

2023-01-21 05:40 UTC, merged